// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: proto/publicrpc/v1/publicrpc.proto

package publicrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	v1 "vebridge/node/proto/gossip/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainID int32

const (
	ChainID_CHAIN_ID_UNSPECIFIED ChainID = 0
	ChainID_CHAIN_ID_SOLANA      ChainID = 1
	ChainID_CHAIN_ID_ETHEREUM    ChainID = 2
)

// Enum value maps for ChainID.
var (
	ChainID_name = map[int32]string{
		0: "CHAIN_ID_UNSPECIFIED",
		1: "CHAIN_ID_SOLANA",
		2: "CHAIN_ID_ETHEREUM",
	}
	ChainID_value = map[string]int32{
		"CHAIN_ID_UNSPECIFIED": 0,
		"CHAIN_ID_SOLANA":      1,
		"CHAIN_ID_ETHEREUM":    2,
	}
)

func (x ChainID) Enum() *ChainID {
	p := new(ChainID)
	*p = x
	return p
}

func (x ChainID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_publicrpc_v1_publicrpc_proto_enumTypes[0].Descriptor()
}

func (ChainID) Type() protoreflect.EnumType {
	return &file_proto_publicrpc_v1_publicrpc_proto_enumTypes[0]
}

func (x ChainID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainID.Descriptor instead.
func (ChainID) EnumDescriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{0}
}

type GetLastHeartbeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLastHeartbeatsRequest) Reset() {
	*x = GetLastHeartbeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastHeartbeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsRequest) ProtoMessage() {}

func (x *GetLastHeartbeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsRequest.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{0}
}

type GetLastHeartbeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GetLastHeartbeatsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetLastHeartbeatsResponse) Reset() {
	*x = GetLastHeartbeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastHeartbeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsResponse) ProtoMessage() {}

func (x *GetLastHeartbeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsResponse.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastHeartbeatsResponse) GetEntries() []*GetLastHeartbeatsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetCurrentGuardianSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentGuardianSetRequest) Reset() {
	*x = GetCurrentGuardianSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentGuardianSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGuardianSetRequest) ProtoMessage() {}

func (x *GetCurrentGuardianSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGuardianSetRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentGuardianSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{2}
}

type GetCurrentGuardianSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuardianSet *GuardianSet `protobuf:"bytes,1,opt,name=guardian_set,json=guardianSet,proto3" json:"guardian_set,omitempty"`
}

func (x *GetCurrentGuardianSetResponse) Reset() {
	*x = GetCurrentGuardianSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentGuardianSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGuardianSetResponse) ProtoMessage() {}

func (x *GetCurrentGuardianSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGuardianSetResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentGuardianSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentGuardianSetResponse) GetGuardianSet() *GuardianSet {
	if x != nil {
		return x.GuardianSet
	}
	return nil
}

type GuardianSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Guardian set index
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// List of guardian addresses as human-readable hex-encoded (leading 0x) addresses.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *GuardianSet) Reset() {
	*x = GuardianSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuardianSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardianSet) ProtoMessage() {}

func (x *GuardianSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardianSet.ProtoReflect.Descriptor instead.
func (*GuardianSet) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{4}
}

func (x *GuardianSet) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GuardianSet) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GetLastHeartbeatsResponse_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Verified, hex-encoded (with leading 0x) guardian address. This is the guardian address
	// which signed this heartbeat. The GuardianAddr field inside the heartbeat
	// is NOT verified - remote nodes can put arbitrary data in it.
	VerifiedGuardianAddr string `protobuf:"bytes,1,opt,name=verified_guardian_addr,json=verifiedGuardianAddr,proto3" json:"verified_guardian_addr,omitempty"`
	// Base58-encoded libp2p node address that sent this heartbeat, used to
	// distinguish between multiple nodes running for the same guardian.
	P2PNodeAddr string `protobuf:"bytes,2,opt,name=p2p_node_addr,json=p2pNodeAddr,proto3" json:"p2p_node_addr,omitempty"`
	// Raw heartbeat received from the network. Data is only as trusted
	// as the guardian node that sent it - none of the fields are verified.
	RawHeartbeat *v1.Heartbeat `protobuf:"bytes,3,opt,name=raw_heartbeat,json=rawHeartbeat,proto3" json:"raw_heartbeat,omitempty"`
}

func (x *GetLastHeartbeatsResponse_Entry) Reset() {
	*x = GetLastHeartbeatsResponse_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastHeartbeatsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastHeartbeatsResponse_Entry) ProtoMessage() {}

func (x *GetLastHeartbeatsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publicrpc_v1_publicrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastHeartbeatsResponse_Entry.ProtoReflect.Descriptor instead.
func (*GetLastHeartbeatsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetLastHeartbeatsResponse_Entry) GetVerifiedGuardianAddr() string {
	if x != nil {
		return x.VerifiedGuardianAddr
	}
	return ""
}

func (x *GetLastHeartbeatsResponse_Entry) GetP2PNodeAddr() string {
	if x != nil {
		return x.P2PNodeAddr
	}
	return ""
}

func (x *GetLastHeartbeatsResponse_Entry) GetRawHeartbeat() *v1.Heartbeat {
	if x != nil {
		return x.RawHeartbeat
	}
	return nil
}

var File_proto_publicrpc_v1_publicrpc_proto protoreflect.FileDescriptor

var file_proto_publicrpc_v1_publicrpc_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70,
	0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x83, 0x02, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x1a, 0x9c, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x34, 0x0a,
	0x16, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x67, 0x75, 0x61, 0x72, 0x64, 0x69,
	0x61, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x22, 0x0a, 0x0d, 0x70, 0x32, 0x70, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x32, 0x70, 0x4e,
	0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x39, 0x0a, 0x0d, 0x72, 0x61, 0x77, 0x5f, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x0c, 0x72, 0x61, 0x77, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x5d, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x67, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x5f,
	0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61,
	0x6e, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x67, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65,
	0x74, 0x22, 0x41, 0x0a, 0x0b, 0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x2a, 0x4f, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x14, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x49, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41,
	0x49, 0x4e, 0x5f, 0x49, 0x44, 0x5f, 0x53, 0x4f, 0x4c, 0x41, 0x4e, 0x41, 0x10, 0x01, 0x12, 0x15,
	0x0a, 0x11, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x49, 0x44, 0x5f, 0x45, 0x54, 0x48, 0x45, 0x52,
	0x45, 0x55, 0x4d, 0x10, 0x02, 0x32, 0xee, 0x01, 0x0a, 0x10, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x12,
	0x26, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x72, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x47, 0x75, 0x61, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x76, 0x65, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x72, 0x70, 0x63, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_publicrpc_v1_publicrpc_proto_rawDescOnce sync.Once
	file_proto_publicrpc_v1_publicrpc_proto_rawDescData = file_proto_publicrpc_v1_publicrpc_proto_rawDesc
)

func file_proto_publicrpc_v1_publicrpc_proto_rawDescGZIP() []byte {
	file_proto_publicrpc_v1_publicrpc_proto_rawDescOnce.Do(func() {
		file_proto_publicrpc_v1_publicrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_publicrpc_v1_publicrpc_proto_rawDescData)
	})
	return file_proto_publicrpc_v1_publicrpc_proto_rawDescData
}

var file_proto_publicrpc_v1_publicrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_publicrpc_v1_publicrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_publicrpc_v1_publicrpc_proto_goTypes = []interface{}{
	(ChainID)(0),                            // 0: publicrpc.v1.ChainID
	(*GetLastHeartbeatsRequest)(nil),        // 1: publicrpc.v1.GetLastHeartbeatsRequest
	(*GetLastHeartbeatsResponse)(nil),       // 2: publicrpc.v1.GetLastHeartbeatsResponse
	(*GetCurrentGuardianSetRequest)(nil),    // 3: publicrpc.v1.GetCurrentGuardianSetRequest
	(*GetCurrentGuardianSetResponse)(nil),   // 4: publicrpc.v1.GetCurrentGuardianSetResponse
	(*GuardianSet)(nil),                     // 5: publicrpc.v1.GuardianSet
	(*GetLastHeartbeatsResponse_Entry)(nil), // 6: publicrpc.v1.GetLastHeartbeatsResponse.Entry
	(*v1.Heartbeat)(nil),                    // 7: gossip.v1.Heartbeat
}
var file_proto_publicrpc_v1_publicrpc_proto_depIdxs = []int32{
	6, // 0: publicrpc.v1.GetLastHeartbeatsResponse.entries:type_name -> publicrpc.v1.GetLastHeartbeatsResponse.Entry
	5, // 1: publicrpc.v1.GetCurrentGuardianSetResponse.guardian_set:type_name -> publicrpc.v1.GuardianSet
	7, // 2: publicrpc.v1.GetLastHeartbeatsResponse.Entry.raw_heartbeat:type_name -> gossip.v1.Heartbeat
	1, // 3: publicrpc.v1.PublicRPCService.GetLastHeartbeats:input_type -> publicrpc.v1.GetLastHeartbeatsRequest
	3, // 4: publicrpc.v1.PublicRPCService.GetCurrentGuardianSet:input_type -> publicrpc.v1.GetCurrentGuardianSetRequest
	2, // 5: publicrpc.v1.PublicRPCService.GetLastHeartbeats:output_type -> publicrpc.v1.GetLastHeartbeatsResponse
	4, // 6: publicrpc.v1.PublicRPCService.GetCurrentGuardianSet:output_type -> publicrpc.v1.GetCurrentGuardianSetResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_publicrpc_v1_publicrpc_proto_init() }
func file_proto_publicrpc_v1_publicrpc_proto_init() {
	if File_proto_publicrpc_v1_publicrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastHeartbeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastHeartbeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentGuardianSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentGuardianSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuardianSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_publicrpc_v1_publicrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastHeartbeatsResponse_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_publicrpc_v1_publicrpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_publicrpc_v1_publicrpc_proto_goTypes,
		DependencyIndexes: file_proto_publicrpc_v1_publicrpc_proto_depIdxs,
		EnumInfos:         file_proto_publicrpc_v1_publicrpc_proto_enumTypes,
		MessageInfos:      file_proto_publicrpc_v1_publicrpc_proto_msgTypes,
	}.Build()
	File_proto_publicrpc_v1_publicrpc_proto = out.File
	file_proto_publicrpc_v1_publicrpc_proto_rawDesc = nil
	file_proto_publicrpc_v1_publicrpc_proto_goTypes = nil
	file_proto_publicrpc_v1_publicrpc_proto_depIdxs = nil
}
